// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1fJzlRzpXxq4Y-fBAOaS8K6gLr3-8jRY',
    appId: '1:1014348003274:web:f1e0d89ce17c7106240133',
    messagingSenderId: '1014348003274',
    projectId: 'quran-72ff9',
    authDomain: 'quran-72ff9.firebaseapp.com',
    storageBucket: 'quran-72ff9.appspot.com',
    measurementId: 'G-3M0351JPMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2kMvigkjcpl9u1cHaQxtxEbqf0966R6E',
    appId: '1:1014348003274:android:0eb7811ef9204520240133',
    messagingSenderId: '1014348003274',
    projectId: 'quran-72ff9',
    storageBucket: 'quran-72ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhL4j_a_rHKLxyHpdzMRiCTS2eLwl117g',
    appId: '1:1014348003274:ios:a0876831cb94fe8d240133',
    messagingSenderId: '1014348003274',
    projectId: 'quran-72ff9',
    storageBucket: 'quran-72ff9.appspot.com',
    iosClientId: '1014348003274-i9n4k79aduumt5u2leb5mt8n0u2qmja7.apps.googleusercontent.com',
    iosBundleId: 'com.example.qurane2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhL4j_a_rHKLxyHpdzMRiCTS2eLwl117g',
    appId: '1:1014348003274:ios:a0876831cb94fe8d240133',
    messagingSenderId: '1014348003274',
    projectId: 'quran-72ff9',
    storageBucket: 'quran-72ff9.appspot.com',
    iosClientId: '1014348003274-i9n4k79aduumt5u2leb5mt8n0u2qmja7.apps.googleusercontent.com',
    iosBundleId: 'com.example.qurane2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1fJzlRzpXxq4Y-fBAOaS8K6gLr3-8jRY',
    appId: '1:1014348003274:web:4823e152660c3be7240133',
    messagingSenderId: '1014348003274',
    projectId: 'quran-72ff9',
    authDomain: 'quran-72ff9.firebaseapp.com',
    storageBucket: 'quran-72ff9.appspot.com',
    measurementId: 'G-4YW9LSVCY8',
  );
}
